# Shell variables
# Generated by 'wal'
wallpaper='/home/masbossun/Pictures/jerry-zhang-9u5Lw227Rb0-unsplash.jpg'

# Special
background='#11161c'
foreground='#c5c7c8'
cursor='#c5c7c8'

# Colors
color0='#11161c'
color1='#66717A'
color2='#8B8378'
color3='#5D7081'
color4='#727B83'
color5='#7B838A'
color6='#8B9194'
color7='#c5c7c8'
color8='#898b8c'
color9='#66717A'
color10='#8B8378'
color11='#5D7081'
color12='#727B83'
color13='#7B838A'
color14='#8B9194'
color15='#c5c7c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
