--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/masbossun/Pictures/jerry-zhang-9u5Lw227Rb0-unsplash.jpg"

-- Special
background="#11161c"
foreground="#c5c7c8"
cursor="#c5c7c8"

-- Colors
color0="#11161c"
color1="#66717A"
color2="#8B8378"
color3="#5D7081"
color4="#727B83"
color5="#7B838A"
color6="#8B9194"
color7="#c5c7c8"
color8="#898b8c"
color9="#66717A"
color10="#8B8378"
color11="#5D7081"
color12="#727B83"
color13="#7B838A"
color14="#8B9194"
color15="#c5c7c8"
