# Shell variables
# Generated by 'wal'
wallpaper='/home/masbossun/Pictures/osman-rana-GXEZuWo5m4I-unsplash.jpg'

# Special
background='#131313'
foreground='#9ac1ca'
cursor='#9ac1ca'

# Colors
color0='#131313'
color1='#616164'
color2='#9D5235'
color3='#D1633C'
color4='#976554'
color5='#C49753'
color6='#58748A'
color7='#9ac1ca'
color8='#6b878d'
color9='#616164'
color10='#9D5235'
color11='#D1633C'
color12='#976554'
color13='#C49753'
color14='#58748A'
color15='#9ac1ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
